# Generated by Django 5.0.2 on 2024-02-26 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/stock_listings/')),
                ('category', models.CharField(choices=[('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('TOYS', 'Toys'), ('MIXED GOODS', 'Mixed Goods'), ('RETURNS', 'Returns')], default='MIXED GOODS', max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('is_sold', models.BooleanField(db_index=True, default=False, verbose_name='is sold')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['title', 'is_sold', '-created_at'],
            },
        ),
    ]
