# Generated by Django 5.0.2 on 2024-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_stock', '0003_remove_stocklisting_owner_stocklisting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklisting',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('TOYS', 'Toys'), ('MIXED GOODS', 'Mixed Goods'), ('RETURNS', 'Returns'), ('CAR PARTS', 'Car Parts')], default='MIXED GOODS', max_length=50),
        ),
    ]
